-- Migration: 021_admin_system_setup.sql: Setup for Admin RAG and Question Staging

-- 1. Enable Vector Extension (for RAG)
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================
-- SYSTEM 1: TEXTBOOK RAG
-- ============================================================

-- Table: Textbooks Metadata
CREATE TABLE IF NOT EXISTS public.textbooks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  subject TEXT NOT NULL, -- 'Physics', 'Chemistry', 'Maths'
  board TEXT NOT NULL,   -- 'CBSE', 'TSBIE', 'ICSE', etc.
  class_level TEXT NOT NULL, -- '11', '12'
  file_path TEXT NOT NULL, -- Supabase Storage path
  status TEXT DEFAULT 'processing', -- 'processing', 'ready', 'error'
  error_message TEXT,
  uploaded_at TIMESTAMPTZ DEFAULT NOW(),
  uploaded_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- Table: Textbook Content Chunks (with Embeddings)
CREATE TABLE IF NOT EXISTS public.textbook_chunks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  textbook_id UUID NOT NULL REFERENCES public.textbooks(id) ON DELETE CASCADE,
  content TEXT NOT NULL,             -- The actual text chunk
  page_number INTEGER,               -- Page number in PDF
  chunk_index INTEGER,               -- Order within the file
  embedding vector(768),             -- 768 dimensions for Gemini text-embedding-004
  metadata JSONB DEFAULT '{}'::jsonb -- Extra info (chapter title, section)
);

-- Index for Vector Similarity Search
-- Uses IVFFlat index for faster approximate nearest neighbor search
-- Note: This requires some data to be effective, usually added after data load
-- For now we create it, but it might need rebuilding later
CREATE INDEX IF NOT EXISTS idx_textbook_chunks_embedding 
  ON public.textbook_chunks 
  USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 100);

-- RLS Policies for RAG Tables
ALTER TABLE public.textbooks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.textbook_chunks ENABLE ROW LEVEL SECURITY;

-- Admins can do everything, standard users can only read processed content (via RPC)
-- Admins can do everything, standard users can only read processed content (via RPC)
-- For now, allowing all authenticated users to read for development speed
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE schemaname = 'public' 
      AND tablename = 'textbooks' 
      AND policyname = 'Allow read access to authenticated users'
  ) THEN
    CREATE POLICY "Allow read access to authenticated users"
      ON public.textbooks FOR SELECT TO authenticated USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE schemaname = 'public' 
      AND tablename = 'textbooks' 
      AND policyname = 'Allow insert/update to authenticated users (admin)'
  ) THEN
    CREATE POLICY "Allow insert/update to authenticated users (admin)"
      ON public.textbooks FOR ALL TO authenticated USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE schemaname = 'public' 
      AND tablename = 'textbook_chunks' 
      AND policyname = 'Allow read access to chunks'
  ) THEN
    CREATE POLICY "Allow read access to chunks"
      ON public.textbook_chunks FOR SELECT TO authenticated USING (true);
  END IF;
END$$;

-- ============================================================
-- SYSTEM 2: QUESTION STAGING (ADMIN UPLOAD)
-- ============================================================

-- Table: Staging Questions
-- This holds questions uploaded via CSV before they are published
CREATE TABLE IF NOT EXISTS public.staging_questions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  batch_id UUID,                 -- To group uploads
  
  -- Raw Data from CSV
  source_text TEXT,              -- Question text
  subject TEXT,
  topic TEXT,
  subtopic TEXT,
  difficulty TEXT,
  exam_profile TEXT,
  
  -- AI Enriched Data (generated by Edge Function)
  enriched_data JSONB,           -- Stores { solution, options, correctIndex, diagram }
  
  -- Status Tracking
  status TEXT DEFAULT 'pending', -- 'pending', 'processing', 'review_needed', 'ready', 'published', 'error'
  error_message TEXT,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- Index for fast filtering by status
CREATE INDEX IF NOT EXISTS idx_staging_questions_status 
  ON public.staging_questions(status);

-- RLS Policies for Staging
ALTER TABLE public.staging_questions ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE schemaname = 'public' 
      AND tablename = 'staging_questions' 
      AND policyname = 'Allow all access to authenticated users (admin)'
  ) THEN
    CREATE POLICY "Allow all access to authenticated users (admin)"
      ON public.staging_questions FOR ALL TO authenticated USING (true);
  END IF;
END$$;

-- ============================================================
-- FUNCTIONS
-- ============================================================

-- Function: Match Syllabus Content (RAG Search)
-- Finds relevant textbook chunks for a given query embedding
CREATE OR REPLACE FUNCTION public.match_syllabus_content(
  query_embedding vector(768),
  match_threshold float,
  match_count int,
  filter_subject text DEFAULT NULL,
  filter_board text DEFAULT NULL
)
RETURNS TABLE (
  id uuid,
  content text,
  textbook_title text,
  similarity float
)
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
  RETURN QUERY
  SELECT
    chunk.id,
    chunk.content,
    tb.title as textbook_title,
    1 - (chunk.embedding <=> query_embedding) as similarity
  FROM public.textbook_chunks chunk
  JOIN public.textbooks tb ON chunk.textbook_id = tb.id
  WHERE 1 - (chunk.embedding <=> query_embedding) > match_threshold
  AND (filter_subject IS NULL OR tb.subject = filter_subject)
  AND (filter_board IS NULL OR tb.board = filter_board)
  ORDER BY chunk.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- Grant Execute
GRANT EXECUTE ON FUNCTION public.match_syllabus_content(vector, float, int, text, text) TO authenticated;

-- Notify Pgrst to reload schema
NOTIFY pgrst, 'reload schema';
