
import { z } from "zod";

export const QuestionSchema = z.object({
  questionText: z.string(),
  // STRICT: Must have exactly 4 options to match the UI layout
  options: z.array(z.object({ text: z.string() }))
    .length(4, { message: "Options array must contain exactly 4 items." }),
  // STRICT: Index must be valid for the options array
  correctOptionIndex: z.number().int().min(0).max(3),
  timeTargets: z.object({
    jee_main: z.number(),
    cat: z.number(),
    eamcet: z.number()
  }),
  // T.A.R. (Optimal Path)
  optimal_path: z.object({
    available: z.boolean(),
    steps: z.array(z.string())
  }).nullable().optional(),
  // D.E.E.P. (Full Solution)
  full_solution: z.object({
    phases: z.array(z.object({
      label: z.enum(['DIAGNOSE', 'EXTRACT', 'EXECUTE', 'PROOF']),
      content: z.string()
    }))
  }).optional(),

  // Legacy (Optional)
  theOptimalPath: z.object({
    exists: z.boolean(),
    preconditions: z.string().optional(),
    steps: z.array(z.string()),
    sanityCheck: z.string().optional()
  }).optional(),
  fullStepByStep: z.object({
    steps: z.array(z.string())
  }).optional(),
  // FSM Tag: kebab-case pattern identifier for grouping similar problems
  fsmTag: z.string().regex(
    /^[a-z0-9]+(-[a-z0-9]+)*$/,
    { message: "fsmTag must be lowercase kebab-case (e.g., 'ratio-inverse-prop')" }
  ).optional(),
  // Visual description - prompt for image model (generated by text model)
  visualDescription: z.string().nullable().optional(),
  // Hosted diagram URL (populated by diagram worker)
  diagramUrl: z.string().nullable().optional(),
  // Whether this question requires a diagram
  diagramRequired: z.boolean().optional(),
  // Difficulty level for dynamic timer calculation
  difficulty: z.enum(['Easy', 'Medium', 'Hard']).optional(),
});

export type QuestionItem = z.infer<typeof QuestionSchema>;

